version: "3.7"

services:
   explorer.db:
      image: postgres:11
      restart: always
      volumes:
         - ./pgdata:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=gexplorer
         - POSTGRES_USER=${PG_USER}
         - POSTGRES_PASSWORD=${PG_PASS}
   
   explorer.app:
      build: .
      ports:
         - 8092:80